---

- name: Check if ta.key exists
  stat:
    path: "{{ openvpn_configuration_directory }}/ta.key"
  register: ta_key

- name: setup the ta.key file
  ansible.builtin.include_tasks:
    file: 'easy-rsa.yml'
  when: not ta_key.stat.exists

- name: ensure ccd directory exists
  ansible.builtin.file:
    path: "{{ openvpn_configuration_directory }}/ccd"
    state: directory
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0750"

- name: create ccd/host files
  ansible.builtin.template:
    src: ccd.conf.j2
    dest: "{{ openvpn_configuration_directory }}/ccd/{{ item }}"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  with_items: '{{ ccd_hosts | default([]) }}'

- name: place server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_configuration_directory }}/server.conf"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn
