---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: openvpn-fedora-latest
    image: fedora:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fedora-latest
