---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: openvpn-debian-stable
    image: debian:stable
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-stable
